import Head from "next/head";
import Slide from "../components/Slide";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sarcia's Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen bg-slate-100">
        <div className="lg:w-5/6 lg:mx-auto bg-slate-500 h-full">
          <Slide />
        </div>
      </main>
    </>
  );
}
